Config:
  ForceTime: -1.0             # Foce specific time of day from 0.0 to 1.0, negative values disable feature.
  TimeUpdateRate: 1.0         # Update rate for the game time, 1.0 is vanilla rate.

  LightsOn: 0.77              # Time when world lights are enabled.
  LightsOff: 0.27             # Time when world lights are disabled.

  Console: true               # Show console window.
  ShaderLoader: true          # Use build in shader loader, place shaders in the game\shaders folder.
  ShaderCompiler: false       # Enable shader compiler, place shader sources in the game\fx folder.
  X360Effects: false          # Enable light trails.
  LiveReload: false           # Live reload config files when game loses focus.
  Editor: false               # Enable UI for editing.
  SkipFE: false               # Allows to enter game faster by skipping all the frontend.
  HK_ShaderReload: 0          # Hot key to live recompile and reload shaders, source code needs to be placed in game\fx folder.