Config:
  Console: false              # Show console window.
  ShaderLoader: true          # Use build in shader loader, place shaders in the game\shaders folder.
  ShaderCompiler: false       # Enable shader compiler, place shader sources in the game\fx folder.
  X360Effects: false          # Enable light trails.
  LiveReload: false           # Live reload config files when game loses focus.
  Editor: false               # Enable UI for editing.
  SkipFE: false               # Allows to enter game faster by skipping all the frontend.
  CarVinylPaintFix: true      # Make vinyls to not be affected by car paint.
  BrakeGlow: true             # Enable brake rotor glow.
  GodRays: true               # Enable god rays effect.
  Bloom: true                 # Enable bloom effect.
  RealFeReflections: true     # Enable Real Front End reflections.
  WorldVertexColor: false     # Enable baked world vertex colors.
  CarVertexColor: true        # Enable baked car vertex colors.
  TunnelWetnessFix: true      # Dynamically removes puddles from the tunnels.
  DisableNightShadows: true   # Disable shadowmap rendering at night to improve performance.
  MSAAx8: false               # Force MSAA 8x sample count.
  CustomMeshDist: 500         # Default max distance for custom meshes.
  MaxLights: -1               # Max number of lights on scene.

Time:
  ForceTime: -1.0             # Foce specific time of day from 0.0 to 1.0, negative values disable feature.
  TimeUpdateRate: 1.0         # Update rate for the game time, 1.0 is vanilla rate.
  LightsOn: 0.77              # Time when world lights are enabled.
  LightsOff: 0.24             # Time when world lights are disabled.
  WetTime: 2.0                # Time for the road to get fully wet.
  DryTime: 30.0               # Time for the road to get fully dry.
  RandomStartupTime: false    # Random game time at start.
  RealTime: false             # Use real time from PC in the game.
  SunAzimuth: 0.0             # Angle in deegrees of the initial sun azimuth.

Blur:
  MinSpeed: 25.0              # Minimum speed for blur to activate.
  MaxSpeed: 325.0             # Speed at wich blur get maximum strenght.
  Depth: 150.0                # Maximum distance for object to be affected by blur.

Hotkeys:
  ShaderReload: 0             # Hot key to live recompile and reload shaders, source code needs to be placed in game\fx folder.
  ToggleEditor: 114           # Hot key to toggle UI Editor visibility (F3 by default).

Rain:
  DryTime: 10.0               # Time in minutes between rains.
  DryTimeRandom: 5.0          # Random part is added to the dry time.
  LightTime: 1.0              # Time in minutes for the light rain to last.
  LightTimeRandom: 1.0        # Random part is added to the light time.
  HeavyTime: 3.0              # Time in minutes for the heavy rain to last.
  HeavyTimeRandom: 3.0        # Random part is added to the heavy time.
  LightningTimeOut: 15.0      # Time in seconds between lightning strikes.
  RainCloudsTexture: true     # Transition to rain clouds texture.

WindowGlow:
  Override: true              # Use window color from config, rather then from texture properties.
  Color: [1.0, 0.8, 0.6]      # Window glow color at night.
  Power: 5                    # Window glow color multiplier.

Filter:
  Texture: FILTER_DEFAULT     # LUT Filter to be used in game for color correction.
  Power: 1.0                  # Power of the color correction effect.