Config:
  ForceTime: -1.0             # Foce specific time of day from 0.0 to 1.0, negative values disable feature.
  TimeUpdateRate: 1.0         # Update rate for the game time, 1.0 is vanilla rate.

  LightsOn: 0.72              # Time when world lights are enabled.
  LightsOff: 0.28             # Time when world lights are disabled.

  Console: true               # Show console window.
  ShaderLoader: true          # Use build in shader loader, place shaders in the game\shaders folder.

  LiveReload: false           # Live reload config files when game loses focus.
  HK_ShaderReload: 0          # Hot key to live recompile and reload shaders, source code needs to be placed in game\fx folder.